"""Regenerate the easydiffraction space-group table (re/06, A105, EB-42).

For every space-group setting core accepts (gemmi's canonical ``xhm()`` names),
find the easydiffraction ``(name_h_m, coord_system_code)`` whose symmetry
operations equal gemmi's (as sets; translations mod 1). The table is written to
``src/powderline/gateways/easydiffraction/space_group_table.py`` so the schema
validates in environments without easydiffraction.

Needs easydiffraction (the ``easydiff`` env). ``--check`` compares instead of
writing (the test ``tests/test_easydiffraction_space_groups.py`` runs it).

Usage: pixi run -e easydiff python scripts/generate_easydiffraction_space_groups.py [--check]
"""

from __future__ import annotations

import sys
from fractions import Fraction
from importlib.metadata import version
from pathlib import Path

import gemmi

TABLE = Path(__file__).parent.parent / "src" / "powderline" / "gateways" / "easydiffraction" / "space_group_table.py"


def _gemmi_ops(sg: gemmi.SpaceGroup) -> frozenset:
    ops = set()
    for op in sg.operations():
        rot = tuple(Fraction(v, op.DEN) for row in op.rot for v in row)
        tran = tuple(Fraction(v, op.DEN) % 1 for v in op.tran)
        ops.add((rot, tran))
    return frozenset(ops)


def _symop_ops(symops: list[str]) -> frozenset:
    """easydiffraction's ``'x,y,z'``-style operations as (rotation, translation mod 1)."""
    ops = set()
    for text in symops:
        op = gemmi.Op(text.replace(" ", ""))
        rot = tuple(Fraction(v, op.DEN) for row in op.rot for v in row)
        tran = tuple(Fraction(v, op.DEN) % 1 for v in op.tran)
        ops.add((rot, tran))
    return frozenset(ops)


def build() -> dict[str, tuple[str, str, bool]]:
    """``{xhm: (name_h_m, coord_system_code, is_default_code)}`` for every matched setting.

    ``name_h_m`` is the short symbol a structure accepts (cryspy's
    ``ACCESIBLE_NAME_HM_SHORT``, one per IT number); the code must be one the
    structure accepts for it, and the default is the first of those.
    """
    from cryspy.A_functions_base.function_2_space_group import (
        ACCESIBLE_NAME_HM_SHORT,
        get_it_coordinate_system_codes_by_it_number,
        get_it_number_by_name_hm_short,
    )
    from easydiffraction.crystallography.space_groups import SPACE_GROUPS

    short = {get_it_number_by_name_hm_short(name): name for name in ACCESIBLE_NAME_HM_SHORT}
    by_ops: dict[frozenset, tuple[str, str, bool]] = {}
    for record in SPACE_GROUPS.values():
        number, code = record["IT_number"], record["IT_coordinate_system_code"] or ""
        codes = tuple(get_it_coordinate_system_codes_by_it_number(number))
        if codes and code not in codes or not codes and code:
            continue  # an internal table entry a structure refuses (e.g. IT 149 'r'); unusable
        by_ops.setdefault(_symop_ops(record["symop"]), (short[number], code, not codes or code == codes[0]))
    table = {}
    for sg in gemmi.spacegroup_table():
        match = by_ops.get(_gemmi_ops(sg))
        if match is not None:
            table[sg.xhm()] = match
    return table


def render(table: dict[str, tuple[str, str, bool]]) -> str:
    lines = [
        '"""easydiffraction space-group names for core\'s canonical settings (generated; do not edit).',
        "",
        "Generated by ``scripts/generate_easydiffraction_space_groups.py`` from easydiffraction",
        f"{version('easydiffraction')}: gemmi's canonical extended H-M name -> easydiffraction",
        "``(name_h_m, coord_system_code, is_default_code)`` with the same symmetry operations;",
        "``is_default_code``: the code is the one a structure takes when only the name is set.",
        "Settings missing here have no easydiffraction equivalent (EB-42).",
        '"""',
        "",
        "SPACE_GROUPS: dict[str, tuple[str, str, bool]] = {",
    ]
    lines += [f"    {xhm!r}: ({name!r}, {code!r}, {default!r})," for xhm, (name, code, default) in table.items()]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    text = render(build())
    if "--check" in sys.argv:
        current = TABLE.read_text(encoding="utf-8") if TABLE.exists() else ""
        if current != text:
            print(f"{TABLE} is out of date; regenerate it", file=sys.stderr)
            return 1
        return 0
    TABLE.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TABLE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
